version: '3'

services:
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./db/:/root/db/
    networks:
      - back

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gems:/usr/local/bundle
    networks:
      - back
    ports:
      - "3000:3000"
    depends_on:
      - db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./docker/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      - ./docker/login-ip.php:/var/www/html/plugins-enabled/login-password-ip.php
    networks:
      - back
    depends_on:
      - db

volumes:
  gems:
  db:

networks:
  back:
