version: '3'

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - back

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
      - gems:/usr/local/bundle
    networks:
      - back
    ports:
      - "3000:3000"

    depends_on:
      - db

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - back
    depends_on:
      - db

volumes:
  gems:
  db:

networks:
  back:
